# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5cbcdbb469e5b8b923049e2d3c7dc82613e1cc920e47dac12be6fc39a7b400133ed819eec1eab174eb588224fa81c1319ca4ad87eead7c5efe2ff9a7a5ef448

test:
  secret_key_base: c730ca0843a7d728878b5ae9d4ad4472f90c226d5bf53acd1c7e7195e11ddbf3adbc52d61ce6523623dff3f22fd7455fcb788652a7571c38b036ae4a9441ab56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
